name: XRunPE
main: ZtechNetwork\XRunPE
api: [1.10.0-BETA]
version: 1.0.0.0
author: ZtechNetwork [LeronDoesGaming]

commands:
      xr:
        usage: /xr <quit/create>
        description: Main Command for creating XRun games and leaving the game.
